name: Build Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            args: ""
          - os: macos-latest
            args: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          releaseBody: "Auto build release"
          releaseDraft: false
          prerelease: false

          # 非常重要
          uploadUpdaterJson: true

          # 优先使用 setup.exe 做 windows 更新
          updaterJsonPreferNsis: true

          args: ${{ matrix.args }}
